version: '3'
services:
  python3:
    restart: always
    build: .
    container_name: 'python3-1'
    working_dir: '/root/src'
    tty: true
    volumes:
      - ${SRC_PATH}:/root/src
  chrome:
    image: selenium/standalone-chrome:latest
    shm_size: 6gb